name: Release

on:
  push:
    tags:
      - 'cli-*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set env
      run: |
        echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Upload image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.cli
        tags: stevechavez/pgadmin-schema-diff:latest,stevechavez/pgadmin-schema-diff:${{ env.VERSION }}